### ISSUE TITLE
Standard in and out using the command line interface

### ISSUE THREAD

**Issue by jdeck88** [PlantPhenoOntology/ppo_pre_reasoner#2]
Great if we can have standard in and standard out using the command line interface.  Or, having the ability to specify in and out using command line arguments (supporting both would be optimal).  This would make it easier to use the pre-reasoner with other tools....

**Comment by stuckyb** [comment]
John, could you move this to the ontopilot project?  Thanks.

**Comment by jdeck88** [comment]
ok, i'll just close the issue here and create a new one there... not sure how to "move" an issue between repos.
