### ISSUE TITLE
problem with 1,000-record data set?

### ISSUE THREAD

**Issue by stuckyb** [PlantPhenoOntology/ppo_pre_reasoner#4]
While working with the 1,000-record data set, I noticed there are some cases where a single measurement datum is 'quality measurement of' more than one trait instance.

For example, measurementDatum=0f50f6db211b1109ce170c2fdddb03cf is 'quality measurement of' plantStructurePresence=b433bc85a64208aac8edbcc07fc4fec0 ('leaf presence') and plantStructurePresence=ef6c9d9990f279458359c1e0f41f4f08 ('new above-ground shoot-borne shoot system presence').

I'm not sure if this was intentional or not, but I don't think it makes sense.

**Comment by jdeck88** [comment]
You are correct, that doesn't make sense!

In the process of creating instances, i specify what fields to use that go into creating the HASH value.  For measurement datum i was using measurement value(s), date, and location to create the measurementDatum instance unique hash.  However, the trait instances you are seeing share the same measurementValues, date, and location. Really, i should be adding Observation_ID (Unique for every observation) to the measurementDatum hash, which will in effect make each measurement unique to each observation.  I altered this and pushed a new 1000 record data set which you can test on.

**Comment by stuckyb** [comment]
Perfect, thanks.
