### ISSUE TITLE
Prefix management

### ISSUE THREAD

**Issue by jdeck88** [PlantPhenoOntology/ppo_pre_reasoner#5]
This issue may be more for ontopilot than for this repository, but posting it here it is easier to reference the issue and what is happening. I checked the issues there to see if it was noted but did not see it.

At any rate, there is unpredictable prefix mapping behaviour occurring with reasoned data output.

I posted a file in the Incoming data directory called [unreasoned_data_test] (https://raw.githubusercontent.com/PlantPhenoOntology/ppo_pre_reasoner/master/Incoming/unreasoned_data_test.ttl) that i tested this with.

In this file, we have a specified prefix of:

@prefix ppo:     <http://www.plantphenology.org/id/> .

This prefix is prefix is used in the body of the reasoned output, without being declared in the header of the reasoned output.

Another curiosity is that some prefixes are declared in the header but not used in the body, e.g.:

    <owl:ObjectProperty rdf:about="http://purl.obolibrary.org/obo/OBI_0000295"/>

With      xmlns:obo="http://purl.obolibrary.org/obo/" being declared in the header.

I would expect:

    <owl:ObjectProperty rdf:about="obo:OBI_0000295"/>

**Comment by stuckyb** [comment]
John, this definitely sounds like an issue with OntoPilot.  Would you 
mind posting a bug report there?  It would be easier for me to keep 
track of this if it were with all the other OntoPilot issues.

**Comment by jdeck88** [comment]
ok, i filed the issue there... closing this

**Comment by stuckyb** [comment]
Thanks!
